version: '3'
services:
    composer:
        image: composer:2.7
        environment:
            - COMPOSER_CACHE_DIR=/app/var/cache/composer
        volumes:
            - .:/app
        restart: "no"
#    php:
#        image: php:8.0-cli
#        restart: "no"
#        volumes:
#            - .:/app
#        working_dir: /app
    phpunit:
        image: php:8.2-cli
        restart: "no"
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit
